version: '3'
services:
  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      ports:
        - 15672:15672
      networks:
        - my_network

  router:
    container_name: router
    build:
      context: .
    entrypoint: python3 router/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_ROUTERS=1
    networks:
      - my_network
    depends_on:
      - rabbitmq

  users:
    container_name: users
    build:
      context: .
    entrypoint: python3 users/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_ROUTERS=1
    networks:
      - my_network
    depends_on:
      - router

  histogram:
    container_name: histogram
    build:
      context: .
    entrypoint: python3 histogram/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_ROUTERS=1
    networks:
      - my_network
    depends_on:
      - router

  business:
    container_name: business
    build:
      context: .
    entrypoint: python3 business/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_ROUTERS=1
    networks:
      - my_network
    depends_on:
      - router

  stars5:
    container_name: stars5
    build:
      context: .
    entrypoint: python3 stars5/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_ROUTERS=1
    networks:
      - my_network
    depends_on:
      - router

  funny:
    container_name: funny
    build:
      context: .
    entrypoint: python3 funny/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_ROUTERS=1
    networks:
      - my_network
    depends_on:
      - router

  client:
    container_name: client
    build:
      context: /home/pato/Desktop/distribuidos
      dockerfile: tp2-yelp-reviews/client/Dockerfile
    entrypoint: python3 client/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
    networks:
      - my_network
    volumes:
      - ../data:/data:rw
    depends_on:
      - rabbitmq

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
