version: '3'
services:
  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      ports:
        - 15672:15672
      networks:
        - my_network

  router:
    container_name: router
    build:
      context: router/
    entrypoint: python3 main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
    networks:
      - my_network
    depends_on:
      - rabbitmq

  users:
    container_name: users
    build:
      context: users/
    entrypoint: python3 main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
    networks:
      - my_network
    depends_on:
      - router

  client:
    container_name: client
    build:
      context: /home/pato/Desktop/distribuidos
      dockerfile: tp2-yelp-reviews/client/Dockerfile
    entrypoint: python3 client/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
    networks:
      - my_network
    volumes:
      - ../data:/data:rw
    depends_on:
      - rabbitmq

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
