version: '3'
services:
  rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: rabbitmq
      ports:
        - 15672:15672
      networks:
        - my_network

  router:
    build:
      context: .
    entrypoint: python3 router/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
    networks:
      - my_network
    depends_on:
      - rabbitmq

  histogram_mapper:
    build:
      context: .
    entrypoint: python3 histogram/mapper_main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_ROUTERS=2
    networks:
      - my_network
    depends_on:
      - router

  users:
    container_name: users
    build:
      context: .
    entrypoint: python3 users/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_MAPPERS=2
    networks:
      - my_network
    depends_on:
      - router

  histogram:
    container_name: histogram
    build:
      context: .
    entrypoint: python3 histogram/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_MAPPERS=2
    networks:
      - my_network
    depends_on:
      - router

  business:
    container_name: business
    build:
      context: .
    entrypoint: python3 business/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_MAPPERS=2
    networks:
      - my_network
    depends_on:
      - router

  stars5:
    container_name: stars5
    build:
      context: .
    entrypoint: python3 stars5/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=2
      - N_MAPPERS=2
    networks:
      - my_network
    depends_on:
      - router

  stars5_mapper:
    build:
      context: .
    entrypoint: python3 stars5/mapper_main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_ROUTERS=2
    networks:
      - my_network
    depends_on:
      - router

  comment:
    container_name: comment
    build:
      context: .
    entrypoint: python3 comment/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_MAPPERS=5
    networks:
      - my_network
    depends_on:
      - router

  comment_mapper:
    build:
      context: .
    entrypoint: python3 comment/mapper_main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_ROUTERS=2
    networks:
      - my_network
    depends_on:
      - router

  funny:
    container_name: funny
    build:
      context: .
    entrypoint: python3 funny/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_MAPPERS=2
    networks:
      - my_network
    depends_on:
      - router

  funny_mapper:
    build:
      context: .
    entrypoint: python3 funny/mapper_main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_ROUTERS=2
    networks:
      - my_network
    depends_on:
      - router

  client:
    container_name: client
    build:
      context: /home/pato/Desktop/distribuidos
      dockerfile: tp2-yelp-reviews/client/Dockerfile
    entrypoint: python3 client/main.py
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
    networks:
      - my_network
    volumes:
      - ../data:/data:rw
    depends_on:
      - rabbitmq

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
