version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - my_network

  router:
    build:
      context: .
    entrypoint: python3 -m router.main
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
    networks:
      - my_network
    depends_on:
      - rabbitmq

  histogram_mapper:
    build:
      context: .
    entrypoint: python3 -m histogram.mapper_main
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_REPLICAS=1
    networks:
      - my_network
    depends_on:
      - router

  users:
    container_name: users
    build:
      context: .
    entrypoint: python3 -m users.main
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_REPLICAS=1
    networks:
      - my_network
    depends_on:
      - router

  histogram:
    container_name: histogram
    build:
      context: .
    entrypoint: python3 -m histogram.main
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_REPLICAS=1
    networks:
      - my_network
    depends_on:
      - router

  business:
    container_name: business
    build:
      context: .
    entrypoint: python3 -m business.main
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_REPLICAS=1
    networks:
      - my_network
    depends_on:
      - router

  stars5:
    container_name: stars5
    build:
      context: .
    entrypoint: python3 -m stars5.main
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=2
      - N_REPLICAS=1
    networks:
      - my_network
    depends_on:
      - router

  stars5_mapper:
    build:
      context: .
    entrypoint: python3 -m stars5.mapper_main
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_REPLICAS=1
    networks:
      - my_network
    depends_on:
      - router

  comment:
    container_name: comment
    build:
      context: .
    entrypoint: python3 -m comment.main
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_REPLICAS=1
    networks:
      - my_network
    depends_on:
      - router

  comment_mapper:
    build:
      context: .
    entrypoint: python3 -m comment.mapper_main
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_REPLICAS=1
    networks:
      - my_network
    depends_on:
      - router

  funny:
    container_name: funny
    build:
      context: .
    entrypoint: python3 -m funny.main
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_REPLICAS=1
    networks:
      - my_network
    depends_on:
      - router

  funny_mapper:
    build:
      context: .
    entrypoint: python3 -m funny.mapper_main
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
      - N_REPLICAS=1
    networks:
      - my_network
    depends_on:
      - router

  client:
    container_name: client
    build:
      context: .
    entrypoint: python3 -m client.main
    environment:
      - PYTHONUNBUFFERED=1
      - AMQP_URL=amqp://rabbitmq?connection_attempts=5&retry_delay=5
    networks:
      - my_network
    volumes:
      - ../data:/data:rw
    depends_on:
      - rabbitmq

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
